# Generated by Django 4.0.6 on 2022-10-10 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='description',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='listing',
            name='imageUrl',
            field=models.CharField(max_length=10000),
        ),
    ]
